### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jcdoster** [johanhedin/sdrx#2]
"rtl-sdr_export.h" -- No such file or directory

Is this file not in the current rtlsdr repositories?

**Comment by jcdoster** [comment]
Found the issue. The "#include comment on line 30 of rtl-sdr.h should be "rtl-sdr_export.h" vice <rtl-sdr_export.h> given it's in the same directory. I fixed on my git pull. 

Now, I'm going to check this thing out :) Thx.

**Comment by johanhedin** [comment]
There should not be any need to change the source code files to build sdrx. What steps did you go through to get this error?

**Comment by johanhedin** [comment]
Closing this since it seems that the problem has gone away.
